name:                sausage
version:             0.1.0.0
github:              "jonesnoaht/sausage"
license:             BSD-3-Clause
author:              "Noah Jones"
maintainer:          "noahtjones@gmail.com"
copyright:           "2023 Noah Jones"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sausage#readme>

dependencies:
- base >= 4.7 && < 5
- text
- cassava
- bytestring
- vector
- parsec
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -XDataKinds

library:
  source-dirs: src

executables:
  sausage-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sausage

tests:
  sausage-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sausage
